import Header from "@/components/Header";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "@/app/globals.css";
import {LocalizedStringProvider} from 'react-aria-components/i18n';

// import { I18nProvider } from "@react-aria/i18n";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" data-theme="dark">
      <body className="antialiased font-[IRANSans]">
        <LocalizedStringProvider locale="fa-IR" />
        {/* <I18nProvider locale="fa-IR"> */}
          <SessionProvider>
            <div className="container mt-4 w-11/12 mx-auto ">
              <Header />
              <main>{children}</main>
            </div>{" "}
          </SessionProvider>
        {/* </I18nProvider> */}
      </body>
    </html>
  );
}
